sudo: required
dist: trusty


cache:
  npm: true
  directories:
    - /home/travis/build/hasadna/open_pension/server/data/OpenPensionCSV
    - "$HOME/.npm"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: python
python:
  - 3.6

git:
  lfs_skip_smudge: true

services:
  - docker

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - TRAVIS_CI_OPERATOR=1
    - secure: "HQFd25/fJl5QKxyQEQi6F7x5YL8bcz6QxbxPWIrSHJ86vSxQ2mQJZHwOoH0IgZX6rp4d758j9GW2yX8d0tGA4M5sFBJNNV8ebbh6suFZCaTPD94HNxAq8n4IXs2yvJhScgwP7ihYrhcArNcwkTnS0FkFQhWytlaNcR10AZBdtPxPmsj/zbBDTKrB+Jmme5DtA8EfzkSXfHhhfKhRj48L56F6/Jy7Yrn0c6+HqByyTIeZfHcbE66lSN+ywtaMlIU+OCoksMCgZ9GNCIKLl8ATXF/sVcw2ed1gKlCye5UPL1b2Z04ihEvyTPO6bM8E/cjMjbY5LdBrE41Su7tiyT8DSQ31ou9vAcQxPlICHBnwi3KwFhm0DcQVovcIAu4kt7Klfyr32BxxjBw35+wGom4Wp73q1E5fAPl/RhwWYrZAoQr4ZFhNB1D8n7evPcz9kRHNsUPlGfUKT2O+xd5XK631LLSTfEiotDQLBF+JU1indLTPIVjTfgZNX8Ptc/rICo+BU9wQ0EeHCr06jd4MHlcI5UnWSQOtEMI2gtBfGNKF8B/2QjUdH0Lc4EedVysVSmnOmVdbfuF6TKP34GgTYvk/dAmHCw0qfAO9QovFW/GTCB3+qK72CewXwaoFAnjDUY/mxkSI5X4pkejns2BcYqsjm1yNhAv8DIkmCQG9I8BoEQU="
    - secure: "0cvJpfflmWrwlu1SJ03FEbV+Ku9Dq6d5YNNDYKIyRYdmNQZl885dLTMgMPt49w2e/DaUIUJf/ix+hFXgJrBULmFVR3reggbi4QifhRdin7P/QEN1Bzx80d1/kmTA0Esvo5fXU/yXcKoqL7Rf+JmZjxkCqaNHCx8oUH2uVkupiX1iyIe8gi3r0cgBu6NaR+fZt+OFYVyaW3KZd0vtb1czDXsYxjck01UhPy5oTtiDmkn247jZ+u/qqVcCDBaEJhyknhgdx2EJB1eTXmJedIWHXECb+JXi7CwAcdLIwmGJyYszVaYXHkF4aTYUTRpUqd+BDLIjmSMKGbb6yhZt5mJPFG2bXO3uxV9euK+V8shZdCRxLCwD/9FNqW9Z0oOANdAkm8+G4IodVdKDkK97OZGsZZ+aq9cZ2Gq7KMUXdzrWCMI26krIPglOOA7vf6UcVE7Ixw3yZ0DNFPiDs8SOQMd0CAaZASGA4QgatihIzoKM1Hiob3YBTd7pJyMyUFNoWwml/hENk8vjlTQ7idMAguH0cw2XTnBgdbAsKX6qFlft5YoYJRtzfQj+zTW4Rwn02Sx7g+zGDS/yyg+URh1O+PtHpcMT7EXdnj2pgetm0JaLOocu/h9jbBtgcDL2q1xOO3nXSR1w7mrojb4sbNW0i6ZsF0n1xFjF75AKfuYjPxAeL94="

#before_install:
  #- npm install -g npm@latest codecov
  #- export CHROME_BIN=chromium-browser
  #- export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start
  #- cd /home/travis/build/hasadna/open_pension/client
  #- docker pull hasadna/open-pension-client
  #- docker build -t hasadna/open-pension-client --cache-from hasadna/open-pension-client .
  #- cd /home/travis/build/hasadna/open_pension/server
  #- docker pull hasadna/open-pension-server
  #- docker build -t hasadna/open-pension-server --cache-from hasadna/open-pension-server .
  #- cd /home/travis/build/hasadna/open_pension/
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

install:
  # Server
  #- cd /home/travis/build/hasadna/open_pension/
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server pip install coverage pycodestyle flake8 isort

  # Client
  #- cd /home/travis/build/hasadna/open_pension/client
  #- npm ci
  # CI/CD
  - curl -L https://raw.githubusercontent.com/OriHoch/travis-ci-operator/master/travis_ci_operator.sh > $HOME/bin/travis_ci_operator.sh
  - bash $HOME/bin/travis_ci_operator.sh init
  - travis_ci_operator.sh docker-login
script:
  # Client
  #- cd /home/travis/build/hasadna/open_pension/client
  #- npm run lint
  #- npm run test
  #- npm run e2e

  # Server
  #- cd /home/travis/build/hasadna/open_pension/
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server coverage run --source='.' manage.py test
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server coverage xml
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server pycodestyle --show-source --max-line-length=120 --exclude=pension/migrations --show-pep8 .
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server isort . --recursive --check-only

  - docker build -t hasadna/open-pension-server:latest ./server
  - docker build -t hasadna/open-pension-client:latest ./client

after_script:
  - cd /home/travis/build/hasadna/open_pension && codecov -t 4e44efc7-43b7-42e3-a122-4042d83e19ff

deploy:
  provider: script
  script: bash .travis.sh deploy
  on:
    branch: master
    condition: $TRAVIS_TAG = "" && $TRAVIS_PULL_REQUEST = "false"