sudo: required
dist: trusty

cache:
  npm: true
  directories:
    - /home/travis/build/hasadna/open_pension/server/data/OpenPensionCSV
    - "$HOME/.npm"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: python
python:
  - 3.6

git:
  lfs_skip_smudge: true

services:
  - docker

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1


before_install:
  - npm install -g npm@latest codecov
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd /home/travis/build/hasadna/open_pension/client
  - docker pull hasadna/open-pension-client
  - docker build -t hasadna/open-pension-client --cache-from hasadna/open-pension-client .
  - cd /home/travis/build/hasadna/open_pension/server
  - docker pull hasadna/open-pension-server
  - docker build -t hasadna/open-pension-server --cache-from hasadna/open-pension-server .
  - cd /home/travis/build/hasadna/open_pension/
  - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

install:
  # Server
  - cd /home/travis/build/hasadna/open_pension/
  - docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server pip install coverage pycodestyle flake8 isort

  # Client
  - cd /home/travis/build/hasadna/open_pension/client
  - npm ci

script:
  # Client
  - cd /home/travis/build/hasadna/open_pension/client
  - npm run lint
  - npm run test
  - npm run e2e

  # Server
  - cd /home/travis/build/hasadna/open_pension/
  - docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server coverage run --source='.' manage.py test
  - docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server coverage xml
  - docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server pycodestyle --show-source --max-line-length=120 --exclude=pension/migrations --show-pep8 .
  - docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server isort . --recursive --check-only
- docker
install:
- curl -L https://raw.githubusercontent.com/OriHoch/travis-ci-operator/master/travis_ci_operator.sh > $HOME/bin/travis_ci_operator.sh
- bash $HOME/bin/travis_ci_operator.sh init
- travis_ci_operator.sh docker-login
- docker build -t hasadna/open_pension:latest .
- travis_ci_operator.sh github-update self master "echo foo > bar; git add bar" "testing github self update"
- travis_ci_operator.sh github-update github-yaml-updater master "echo foo > bar; git add bar" "testing travis-ci-operator" OriHoch/github-yaml-updater
- travis_ci_operator.sh github-yaml-update self master test.yaml '{"foo":"bar"}' "testing github yaml update"
- travis_ci_operator.sh github-yaml-update github-yaml-updater master test.yaml '{"foo":"bar"}' "testing travis-ci-operator github yaml update" OriHoch/github-yaml-updater

after_script:
  - cd /home/travis/build/hasadna/open_pension && codecov -t 4e44efc7-43b7-42e3-a122-4042d83e19ff

deploy:
  provider: script
  script: docker push hasadna/open_pension:latest
  on:
    branch: master
    condition: $TRAVIS_TAG = "" && $TRAVIS_PULL_REQUEST = "false"