sudo: required
dist: trusty


cache:
  npm: true
  directories:
    - /home/travis/build/hasadna/open_pension/server/data/OpenPensionCSV
    - "$HOME/.npm"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: python
python:
  - 3.6

git:
  lfs_skip_smudge: true

services:
  - docker

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - TRAVIS_CI_OPERATOR=1
    - secure: "KIOtjMa+xwGxg62BZH6i95xN1aKvzaDX2jxdvi76UruMjlTxgEf7i2k+dU01YXe0ggEaclw5v56GaJ/DHKn+JakXNJzjVkEr/xRiY8TZYW6LXDJvdtygxFinXQaBe/FUtvDqe3RmTTwGcwV6TQVKa1G23doWiUSx8CuDHdvaJ5mDnSrOZVV38ZgqT6zchgzmVGQgY8R6wXUkl/obnmJZLsf2VVPXoKmI6J9MCE7xSDoorONdW52zz9ADzQcX2Fn/CotZR8aAE60NruuFlFeYWZc6Mam1OjbZzGmrfIqU55trjSzLtEvSHqaxAtkpEoOVpeMuErbk2kA8BD0NF78fxtUkJKDfs4kif9Xo5dylan07NNgpKLC8se84a+j9QWTKxLUU2ZWR4jPlaDFBbZzIZ99a0Fw7rcwpTd/Km9TKXwRZPyJMFELUSI3Y1wLR6D7t533dOscrCv5b1eNHZmYnkNnQf5zGPCSGwcrxz2xxvqIQEJWbYFIrzgJy1qRtZw5zEDfLla5acH5cxNikPkU+co1UX0g9WT6oBJs2LgxfWzhDLHDqE5uDlp5WRg6gmfqjbi1hhDradbA73KPDr8Fh/wtqdAktihq4f1pDb2SabQR9GmrfOGGtatpdA5C1ZWxchiugLxdTE4uvbxuxQFVjgS0erx7tj0NGjeUWLm7DhlY="
    - secure: "EIChtWQUfnkIrshLJx+DSElli+K4s59QIbLxb8j3c8iPut9vJAxlYKv8PI+XpMl7AVajzZTZvBiXtW+BrdpSjePGavlxwg7ChsCfK+bfAmhwDyAmpgS0iwNBxRFpZlYGi0hgkolBMi1wbT3qHIfiGgbqsVKOISUyZ30xSl8RLnhnrOebvUO0lS64i01RTL7v+VnoU0tHVWPjVRRx//IEaxTYCncWPfm0F2W9Bm0iiu6ecx+5cT64tIxvZOMmtc1+RZu3dYD6KJ2Xifq6M85xpr71/b2cL5avdOcuJL6PXUeI2EPB/bBBbnPQFe84cT09T6o4y58IGuFHnd05lMkFLg1jO0rAnm03zERtDE1u8BESOzlGo6SCQRp+e/ZQTCXvaWhKZ9JlSnKQaMoFB4YeslZ+TyZoWEjJKPloYASj1fAIfhBmWRDG8JHkzhdblWTLHwqmbk+ontl8DCEDGeV6PtZxc047Gov9z88bg9cwmM96h5NcUl7STMOAJRXxHNQoqJMB1BpZkzABJMbrCv1ip00KqWDLxIhUVmJjzF8Uo3K8VFjYJimg7dYdXNMNcpuSgHDI5eIAqeBD6P7fbKEn6g0IHSrsipOHMSHt68d9FB643aP3lTYBkefRt2JxsPysxEYT/I3hz7K2sf8dfyFnazgUfD0cybZcOwAnElxtntw="


#before_install:
  #- npm install -g npm@latest codecov
  #- export CHROME_BIN=chromium-browser
  #- export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start
  #- cd /home/travis/build/hasadna/open_pension/client
  #- docker pull hasadna/open-pension-client
  #- docker build -t hasadna/open-pension-client --cache-from hasadna/open-pension-client .
  #- cd /home/travis/build/hasadna/open_pension/server
  #- docker pull hasadna/open-pension-server
  #- docker build -t hasadna/open-pension-server --cache-from hasadna/open-pension-server .
  #- cd /home/travis/build/hasadna/open_pension/
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

install:
  # Server
  #- cd /home/travis/build/hasadna/open_pension/
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server pip install coverage pycodestyle flake8 isort

  # Client
  #- cd /home/travis/build/hasadna/open_pension/client
  #- npm ci
  # CI/CD
  - curl -L https://raw.githubusercontent.com/OriHoch/travis-ci-operator/master/travis_ci_operator.sh > $HOME/bin/travis_ci_operator.sh
  - bash $HOME/bin/travis_ci_operator.sh init
  - travis_ci_operator.sh docker-login
script:
  # Client
  - cd /home/travis/build/hasadna/open_pension/client
 # - npm run lint
  #- npm run test
  #- npm run e2e

  # Server
  #- cd /home/travis/build/hasadna/open_pension/
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server coverage run --source='.' manage.py test
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server coverage xml
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server pycodestyle --show-source --max-line-length=120 --exclude=pension/migrations --show-pep8 .
  #- docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec server isort . --recursive --check-only

  - docker build -t hasadna/open-pension-server:latest ./server
  - docker build -t hasadna/open-pension-client:latest ./client

after_script:
  - cd /home/travis/build/hasadna/open_pension && codecov -t 4e44efc7-43b7-42e3-a122-4042d83e19ff

deploy:
  provider: script
  script: bash .travis.sh deploy
  on:
    branch: master
    condition: $TRAVIS_TAG = "" && $TRAVIS_PULL_REQUEST = "false"