version: "3"

volumes:
  db-data:
    external: false

services:
  database:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/db-data
      - ./database:/etc/cron.daily
    env_file:
      - .env.prod

  client:
    image: hasadna/open-pension-client
    build: ./client
    ports:
      - "4200:80"
    environment:
      - SERVICE_PORTS=4200

  server:
    image: hasadna/open-pension-server
    build: ./server
    ports:
      - "8000:8000"
    command: /bin/sh entrypoint.sh
    depends_on:
      - database
    env_file:
      - .env.prod
