version: "3"

volumes:
  db-data:
    external: false

services:
  database:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/db-data
      - ./database:/etc/cron.daily

  client:
    image: versys650/open-pension-client:use-hash
    volumes:
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    environment:
      - SERVICE_PORTS=80
    depends_on:
      - server

  server:
    image: hasadna/open-pension-server
    command: /bin/sh entrypoint.sh
    volumes:
      - ./logs/django:/home/app/server/logs
    depends_on:
      - database
