version: "3"

services:
  proxy:
    image: dockercloud/haproxy
    environment:
      - BALANCE=leastconn
      - EXTRA_GLOBAL_SETTINGS=debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80

  database:
    image: postgres

  client:
    image: client
    build: ../client
    ports:
      - "4200:4200"
    environment:
      - SERVICE_PORTS=4200

  server:
    image: server
    build: ../server
    ports:
      - "8000:8000"
    command: bash -c "gunicorn config.wsgi -b 0.0.0.0:8000"
    depends_on:
      - database

