version: "3"

volumes:
  db-data:
    external: false

services:
  proxy:

  database:
    volumes:
      - db-data:/var/lib/postgresql/db-data
    ports:
      - 5432:5432
    env_file:
      - .env.dev

  client:
    volumes:
      - ../client:/usr/src/app
    env_file:
      - .env.dev

  server:
    volumes:
        - ../server:/home/app/server
    env_file:
      - .env.dev
