version: "3"

volumes:
  db-data:
    external: false

services:
  proxy:

  database:
    volumes:
      - db-data:/var/lib/postgresql/db-data
    env_file:
      - .env.dev

  client:
    volumes:
      - ../client:/usr/src/app
    env_file:
      - .env.dev

  server:
    env_file:
      - .env.dev
