version: "3"

services:
  proxy:
    extends:
      file: docker-compose.common.yml
      service: proxy
    deploy:
      placement:
        constraints: [node.role == manager]

  database:
    extends:
      file: docker-compose.common.yml
      service: database
    volumes:
    # TODO add a volume for db-data on prod.
      - ./database:/etc/cron.daily
      - /var/backups:/var/backups
    env_file:
      - .env.prod
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 20s

  client:
    extends:
      file: docker-compose.common.yml
      service: client
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

  server:
    extends:
      file: docker-compose.common.yml
      service: server
    env_file:
      - .env.prod
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 120s

networks:
  openpension:
    driver: overlay
