version: "3"

volumes:
  db-data:
    external: false

services:
  proxy:
    extends:
      file: docker-compose.common.yml
      service: proxy

  database:
    extends:
      file: docker-compose.common.yml
      service: database
    volumes:
      - db-data:/var/lib/postgresql/db-data
    env_file:
      - .env.dev

  client:
    extends:
      file: docker-compose.common.yml
      service: client

  server:
    extends:
      file: docker-compose.common.yml
      service: server
    env_file:
      - .env.dev

networks:
  openpension:
    driver: overlay
